Adds handling for K8s Readiness/Liveness TCP Probe
Vantiq/vantiq-extension-sources pull request #252
Opened 2021-04-20 00:51 UTC by namirfa

Closes #215 

Adds enhancements to the SDK to support K8s Readiness/Liveness TCP Probes. The TCP socket listener will listen on port 8000 by default, but this can be overridden by specifying the `tcpProbePort` in the `server.config` file.

The TestConnector was also enhanced to be able to set/unset its "health state" via publish/query requests. Not sure if we want to add this for all of the connectors, but that can be done in a separate issue/PR.

Need to add documentation for the new SDK features, and I am currently wrapping up manual tests to make sure that K8s can access the ports.

2021-04-20 00:52 UTC, namirfa commented on extjsdk/src/main/java/io/vantiq/extjsdk/Utils.java
> +        String portString = properties.getProperty("tcpProbePort");
This should be a constant var, not a string. I'll change in a future commit.

2021-04-20 00:53 UTC, namirfa commented on extjsdk/src/main/java/io/vantiq/extjsdk/ExtensionWebSocketClient.java
> +    public static final int QUERY_CHUNK_CODE = 100;
A few formatting cleanups at the top of this file.

2021-04-20 19:11 UTC, fhcarter requested changes
At least one of the sider things is worth looking at.

I think that I'd like to see some notion of healthy/unhealthy rather than exposing the low-level TCP details. It seems like exposing these low-level details will (and has) caused issues with the connector-writer having to track too much internal SDK details rather than a more declarative mechanism.  Maybe there's a core level health setting that employed the future & TCP socket rather than each caller having to understand that.

2021-04-21 00:10 UTC, namirfa commented
@fhcarter 

Added fixes per your comments, ready for re-review.

2021-04-21 21:21 UTC, fhcarter approved these changes
A few minor issues to address but LGTM.

Some constants should be declared as such, a concurrency issue, and a test question.

2021-04-21 21:39 UTC, namirfa commented on testConnector/src/test/java/io/vantiq/extsrc/testConnector/TestTestConnectorCore.java
> -        core.start(3);
The `setup()` method is called before each test run and does the `core.start()`, so I removed it here.

2021-04-21 21:50 UTC, merged