Changing all Vantiq SDK Java uses to have the (newest) same version
Vantiq/vantiq-extension-sources pull request #256
Opened 2021-05-15 17:09 UTC by namirfa

Closes #255 

Updating all of the Vantiq SDK Java dependencies to be version 1.0.28. We still need to sort out the Bintray migration, but this can be left as a placeholder in the meantime.

Also changed some of the dependencies to be testCompiles where applicable, (everyone but the Obj Rec connector).

2021-05-15 17:10 UTC, namirfa commented
Should I add a top-level variable like `vantiqSDKJavaVersion` and include that in each of the compile/testCompile lines?

2021-05-17 18:13 UTC, fhcarter requested changes
Generalize.

Also, do we need to update the repositories list or is that not complete yet.

2021-05-17 18:13 UTC, fhcarter commented on CSVSource/build.gradle
> +    testCompile 'io.vantiq:vantiq-sdk:1.0.28'
I would suggest that for all of these where we want thing to be the same one, that we add an ext variable (`vantiqSdkVersion = 1.0.28`) to the top level `build.gradle` file, and then reference that in all the subproject gradle files.  Then, when this changes to ...29, etc., we only have to change one place.  Like we do for `${jacksonVersion}` in extjsdk.

Note that all the includes that use single ' will have to change to double " to cause the appropriate GString evaluation.

2021-05-17 18:23 UTC, fhcarter approved these changes
LGTM

2021-05-17 18:23 UTC, namirfa commented
@fhcarter 

Generalized the versioning. 

Waiting to test things again once I've migrated the sdk jar to a new host. I'll know in a bit if that means changing the repositories list (probably will need to).

2021-05-18 16:41 UTC, namirfa commented
Update:

Waiting for response from Sonatype regarding our new repo. Once it has been created, we will publish the Vantiq Java SDK jar there. This should mean it will be available via Maven Central and no further changes will be necessary.

2021-05-18 23:42 UTC, rblumer4 commented
> Waiting for response from Sonatype regarding our new repo. Once it has been created, we will publish the Vantiq Java SDK jar there. This should mean it will be available via Maven Central and no further changes will be necessary.

That's good.  But would be good to clean up the build.gradle's & remove the bintray reference there.
Plus will also need to update the README for the sdk itself to no longer use bintray:  https://github.com/Vantiq/vantiq-sdk-java#readme

2021-05-18 23:50 UTC, namirfa commented
> > Waiting for response from Sonatype regarding our new repo. Once it has been created, we will publish the Vantiq Java SDK jar there. This should mean it will be available via Maven Central and no further changes will be necessary.
> 
> That's good. But would be good to clean up the build.gradle's & remove the bintray reference there.
> Plus will also need to update the README for the sdk itself to no longer use bintray: https://github.com/Vantiq/vantiq-sdk-java#readme

Got rid of all the bintray references. My plan was to update the Java SDK README once the jar has been posted to Sonatype and everything is tested. In the meantime, I'll add an issue in that repo.

2021-05-26 18:33 UTC, namirfa commented
@fhcarter @rblumer4 

Just ran extjsdk integration tests (which use the Vantiq SDK) and everything passed as expected. That means the Java SDK was published successfully!

Let me know if things still look good, and I'll close this PR.

2021-05-26 18:45 UTC, steve-langley commented
Just FYI, I removed the bintray reference from the Android build and it seems to work.

2021-05-26 19:06 UTC, fhcarter commented
Still looks fine to me.  And I can find the vantiq SDK on maven, so it seems to be really there...

2021-05-26 19:20 UTC, merged

2021-05-26 21:35 UTC, rblumer4 commented
I'll look at adding a weekly Jenkins job to compile & testcompile the ext-sdk code.
That will at least catch an issue like this earlier...

2021-05-26 23:44 UTC, rblumer4 commented
Added a weekly job to Jenkins that runs `assemble testClasses`
https://jenkins.vantiq.com/jenkins/job/vantiq-extension-sources-and-sdk/

Does not run any tests, because the only available `test` target gets 10 failures right now (and 93 pass).  
I think those tests require external processes to be available, in order to fully pass.  (e.g. udp or opcUA processes)
Is that right @namirfa?     
if you want to run a subset of the tests on Jenkins, we would need separate test targets so that we could run just the basic/passing tests in that job.

2021-05-26 23:57 UTC, namirfa commented
@rblumer4 

That should be fine for now. If I'm understanding correctly, the motivation is just to make sure that everything is compiling so that we can catch something like the bintray issue earlier.

If we think it's worthwhile, we can add a new issue to setup a Jenkins job that runs all of the connector tests. It'll take a bit of work to make sure the Jenkins machine is configured properly and has all the necessary driver libraries, but it's all doable.